variables:
  VERSION: "2.35.2"
  IMAGE_NAME: "wabizapi-mock"

stages:
  - pre_build
  - scan
  - build

cache:
  paths:
    - "model"

.pre_build_protoc: &pre_build_protoc
  image: golang:latest
  tags:
    - run_docker
  script:
    - go get -u google.golang.org/protobuf/cmd/protoc-gen-go
    - GOPATH=$(go env GOPATH); export PATH=$PATH:${GOPATH}/bin
    - 'protoc 
        -I . 
        -I ${GOPATH}/src 
        -I ${GOPATH}/src/github.com/envoyproxy/protoc-gen-validate 
        --proto_path="./protobuf" 
        --go_out=":./" 
        --validate_out="lang=go:." 
        meta.proto general.proto settings.proto status.proto messages.proto users.proto backup.proto internal.proto'

.pre_build_scan: &pre_build_scan
  image: golang:latest
  tags:
    - run_docker
  script:
    - go get -u github.com/securego/gosec/v2/cmd/gosec
    - GOPATH=$(go env GOPATH); export PATH=$PATH:${GOPATH}/bin
    - gosec -exclude G104,G404,G307,G402 ./...


.build_template: &build_image
  script:
    - 'docker build --build-arg VERSION=$VERSION
                    -t $MTR_URL/$IMAGE_NAME:$TAG .'

    - 'echo $MTR_PWD | docker login -u $MTR_USER --password-stdin $MTR_URL'
    - 'docker push $MTR_URL/$IMAGE_NAME:$TAG'


build protoc:
  stage: pre_build
  <<: *pre_build_protoc

scan:
  stage: scan
  <<: *pre_build_scan


build latest:
  stage: build
  tags:
    - run_shell
  variables:
    TAG: latest
  only:
    refs:
      - tags
  <<: *build_image

build versioned:
  stage: build
  tags:
    - run_shell
  variables:
    TAG: v$VERSION
  <<: *build_image
