variables:
  VERSION: "2.35"
  IMAGE_NAME: "wabizapi-mock"
  TAG: "dev"
  PROTOC_BUILDER_IMAGE: mtr.external.otc.telekomcloud.com/digitalmedia-connector/protoc-builder

stages:
  - pre_build
  - check
  - build
  - container_scan_stage

cache:
  key: ${CI_COMMIT_SHORT_SHA}
  paths:
    - "model"

.pre_build_protoc: &pre_build_protoc
  image: docker
  tags:
    - run_docker
  artifacts:
    paths:
      - $PWD/model
    expire_in: 1 hour
  script:
    - apk add make
    - echo $MTR_PWD | docker login $MTR_URL --username $MTR_USER --password-stdin
    - make build-protoc PROTOC_BUILDER_IMAGE=${PROTOC_BUILDER_IMAGE}

.pre_build_test: &pre_build_test
  image: golang
  tags:
    - run_docker
  script:
    - go test ./...

.build_template: &build_image
  tags:
    - run_docker
  image: docker
  before_script:
    - echo $MTR_PWD | docker login -u $MTR_USER --password-stdin $MTR_URL
  script:
    - docker build --build-arg VERSION=$VERSION --tag $MTR_URL/$IMAGE_NAME:$TAG .

    - docker push $MTR_URL/$IMAGE_NAME:$TAG
    - docker image rm $MTR_URL/$IMAGE_NAME:$TAG

build protoc:
  stage: pre_build
  <<: *pre_build_protoc

unit test:
  allow_failure: true
  stage: check
  <<: *pre_build_test

build latest:
  stage: build
  variables:
    TAG: latest
  only:
    refs:
      - tags
  <<: *build_image

build versioned:
  stage: build
  variables:
    TAG: $CI_COMMIT_REF_SLUG
  <<: *build_image
