variables:
  VERSION: "2.35.2"
  IMAGE_NAME: "wabizapi-mock"

stages:
  - pre_build
  - check
  - build
  - post_build

cache:
  paths:
    - "model"

.pre_build_protoc: &pre_build_protoc
  image: golang:latest
  tags:
    - run_docker
  script:
    - GOPATH=$(go env GOPATH); export PATH=$PATH:${GOPATH}/bin
    - export GO111MODULE=off
    - apt-get update && apt-get install -y protobuf-compiler

    - go get google.golang.org/protobuf/cmd/protoc-gen-go
    - go get github.com/envoyproxy/protoc-gen-validate

    - 'protoc 
        -I . 
        -I ${GOPATH}/src 
        -I ${GOPATH}/src/github.com/envoyproxy/protoc-gen-validate 
        --proto_path="./protobuf" 
        --go_out=":./" 
        --validate_out="lang=go:." 
        meta.proto general.proto settings.proto status.proto messages.proto users.proto backup.proto internal.proto'

    -  chmod 777 -R model

.pre_build_scan: &pre_build_scan
  image: golang:latest
  tags:
    - run_docker
  script:
    - go get -u github.com/securego/gosec/v2/cmd/gosec
    - GOPATH=$(go env GOPATH); export PATH=$PATH:${GOPATH}/bin
    - gosec -exclude G104,G404,G307,G402 -severity high ./...

.pre_build_test: &pre_build_test
  image: golang:latest
  tags:
    - run_docker
  script:
    - mkdir -p uploads
    - go test ./...

.build_template: &build_image
  before_script:
    - echo $MTR_PWD | docker login -u $MTR_USER --password-stdin $MTR_URL
  script:
    - 'docker build --build-arg VERSION=$VERSION
                    -t $MTR_URL/$IMAGE_NAME:$TAG .'


    - docker push $MTR_URL/$IMAGE_NAME:$TAG
    - docker image rm $MTR_URL/$IMAGE_NAME:$TAG


# Telekom DevSecOps: Container Scanner
include: 'https://codeshare.workbench.telekom.de/gitlab/teamdevsecops/container-scanning-service/raw/master/container-scan.yml'

.scan_image: &scan_image
  stage: post_build
  before_script:
    - echo $MTR_PWD | docker login -u $MTR_USER --password-stdin $MTR_URL
  artifacts:
    paths:
      - anchore-reports/*.json
    expire_in: 1 hour
  variables:
    IMAGE_TAG_CONTAINER_SCAN: "$MTR_URL/$IMAGE_NAME:$TAG"
  extends: .container_scan


build protoc:
  stage: pre_build
  <<: *pre_build_protoc

unit test:
  stage: check
  <<: *pre_build_test

scan:
  stage: check
  <<: *pre_build_scan


build latest:
  stage: build
  tags:
    - run_shell
  variables:
    TAG: latest
  only:
    refs:
      - tags
  <<: *build_image
  <<: *scan_image

build versioned:
  stage: build
  tags:
    - run_shell
  variables:
    TAG: v$VERSION
  <<: *build_image
  <<: *scan_image

