fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: pretty-format-json
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
